config/routes.rb
Rails.application.routes.draw do

  root :to =>"homes#top"
  devise_for :users
  
  devise_scope :user do
    get '/users', to: 'devise/registrations#new'
  end
  
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get "followings" => "relationships#followings", as: "followings"
    get "followers" => "relationships#followers", as: "followers"
    get "confirm" => "users#confirm", as: "confirm"
  end

  resources :posts do
    resources :post_comments, only: [:create, :destroy, :edit, :update]
    resource :bookmarks, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  get "users/:id/bookmarks", to: "bookmarks#index", as: :bookmark
  get "users/:id/favorites", to: "favorites#index", as: :favorite

  get ' /tags/:id/posts', to: 'posts#search', as: :tag_posts
  get ' /tags/index', to: 'tags#index', as: :tag

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :user_id, uniqueness: { scope: :post_id }
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
before_action :authenticate_user!

  def index
    @user = current_user
    @favorites = @user.favorites.page(params[:page]).per(5)
  end

  def create
    @post = Post.find(params[:post_id])
    @favorite = @post.favorites.new(user_id: current_user.id)
    if @favorite.save
    else
      redirect_to request.referer
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @favorite = @post.favorites.find_by(user_id: current_user.id)
    if @favorite.present?
      @favorite.destroy
    else
      redirect_to request.referer
    end
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_favorite.html.erb
<% if post.user != current_user %>
  <% if post.favorited_by?(current_user) %>
    <%= link_to post_favorites_path(post), method: :delete, remote: true do %>
      <i class="fas fa-heart" aria-hidden="true" style="color: red;"></i>
    <% end %>
  <% else %>
    <%= link_to post_favorites_path(post), method: :post, remote: true do %>
      <i class="fas fa-heart " aria-hidden="true"></i>
    <% end %>
  <% end %>
<% end %>

app/views/favorites/create.js.erb
$('#favorite_button_<%= @post.id %>').html("<%= j(render "favorites/favorite", post: @post) %>");

app/views/favorites/destroy.js.erb
$('#favorite_button_<%= @post.id %>').html("<%= j(render "favorites/favorite", post: @post) %>");

app/views/favorites/index.html.erb
<div class="container">
  <div class="table-responsive">
    <table class='table table-hover table-inverse'>
      <thead>
        <tr>
          <th class="col-7">いいねした投稿</th>
          <th class="col-2"></th>
          <th class="col-3"></th>
        </tr>
      </thead>
      <% @favorites.each do |favorite| %>
        <tbody>
          <tr>
            <td><%= image_tag favorite.post.get_post_image, width: '100%' %></td>
            <td>
              <%= image_tag favorite.post.user.get_profile_image, width: '40px',height: "40px",class:"rounded-circle" %><br>
              <%= link_to favorite.post.user.name, user_path(favorite.post.user) %>
            </td>
            <td>
              <%= link_to favorite.post.title, post_path(favorite.post) %>
              <div id="star-rate<%= favorite.post.id %>"></div>
              <script>
                $('#star-rate<%= favorite.post.id %>').empty();
                $('#star-rate<%= favorite.post.id %>').raty({
                  size      : 36,
                  starOff   : '<%= asset_path('star-off.png') %>',
                  starOn    : '<%= asset_path('star-on.png') %>',
                  starHalf  : '<%= asset_path('star-half.png') %>',
                  half      : true,
                  readOnly  : true,
                  score: <%= favorite.post.star %>,
                });
              </script>
            </td>
          </tr>
        </tbody>
      <% end %>
    </table>
  </div>
  <div class="d-flex justify-content-center">
    <%= paginate @favorites %>
  </div>
</div>