config/routes.rb
Rails.application.routes.draw do

  root :to =>"homes#top"
  devise_for :users
  
  devise_scope :user do
    get '/users', to: 'devise/registrations#new'
  end
  
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get "followings" => "relationships#followings", as: "followings"
    get "followers" => "relationships#followers", as: "followers"
    get "confirm" => "users#confirm", as: "confirm"
  end

  resources :posts do
    resources :post_comments, only: [:create, :destroy, :edit, :update]
    resource :bookmarks, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  get "users/:id/bookmarks", to: "bookmarks#index", as: :bookmark
  get "users/:id/favorites", to: "favorites#index", as: :favorite

  get ' /tags/:id/posts', to: 'posts#search', as: :tag_posts
  get ' /tags/index', to: 'tags#index', as: :tag

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord

  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower

  has_one_attached :profile_image

  validates :name, length: { minimum: 1, maximum: 10 }, uniqueness: true

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.png'
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :authenticate_user!, only: [:edit,:update,:confirm]

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.all.order(created_at: :desc).page(params[:page]).per(5)
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def confirm
    @user = current_user
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/confirm.html.erb
<div class="container">
	<div class="text-center mt-5 mb-5">
		<h4 style="color:red; font-weight:bold;">本当に退会しますか？</h4>
		</br>
		<h5>退会すると、ブックマーク・いいねした投稿、</h5>
		<h5>これまでの投稿履歴が閲覧できなくなります。</h5>
		<h5>(あなたの投稿も同時に削除されます。)</h5>
		<h5>退会する場合は、「退会する」をクリックしてください。</h5>
	</div>
	<div class="text-center">
		<%= link_to 'キャンセル', user_path(current_user), class: "btn btn-primary" %>
		<%= link_to "退会する", user_registration_path, method: :delete, class: "btn btn-danger" %>
	</div>
</div>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>会員情報編集</h2>
      <div class="row">
      <% if @user.errors.any? %>
        <div style = "color: red;">
          <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    </div>
    <%= form_with model:@user, local:true do |f| %>
      <div class="form-group">
        <%= f.label :"ユーザー名" %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
     <div class="form-group">
        <%= f.label :"アイコン" %>
        <%= f.file_field :profile_image, class: "form-control-file", accept: 'image/*' %>
      </div>
      <img id="preview" style="width:200px; height:200px;" class="rounded-circle">
      <script>
        $('#user_profile_image').on('change', function (e) {
          var reader = new FileReader();
          reader.onload = function (e) {
              $("#preview").attr('src', e.target.result);
          }
          reader.readAsDataURL(e.target.files[0]);
      });
      </script>
      <div class="form-group">
        <%= f.label :"自己紹介文" %>
        <%= f.text_area :introduction, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.submit "更新", class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <% if user_signed_in? %>
    <% if @user == current_user %>
      <div class="low my-1 text-right">
        <%= link_to user_confirm_path(current_user) do %>
          <i class="fas fa-user-minus" style="color: red;"></i>退会する
        <% end %>
      </div>
    <% end %>
  <% end %>
  <div class="justify-content-center">
    <div class="low mt-4 mb-2 text-center">
      <%= image_tag @user.get_profile_image, width: '200px',height: "200px",class:"rounded-circle" %>
    </div>
    <div class="low mb-1 text-center">
      <strong><%= @user.name %></strong>
    </div>
    <% if user_signed_in? %>
      <div class="low mb-1 text-center">
        <% if @user == current_user %>
          <%= link_to edit_user_path(current_user), class: "col-1 mx-auto d-block btn btn-outline-secondary" do %>
            <i class="fas fa-cog"></i>
          <% end %>
        <% end %>
        <%= link_to "フォローしている人を見る",user_followings_path(@user) %>
          <%= "|" %>
          <%= link_to "フォロワーを見る",user_followers_path(@user) %>
      </div>
      <div class="low mx-auto mb-2 text-center">
        <% if @user != current_user %>
          <% if current_user.following?(@user) %>
            <%= link_to "フォロー外す", user_relationships_path(@user.id), method: :delete,class:"btn btn-sm btn-success ml-3" %>
          <% else %>
            <%= link_to "フォローする", user_relationships_path(@user.id), method: :post,class:"btn btn-sm btn-outline-success ml-3" %>
          <% end %>
        <% end %>
      </div>
    <% end %>
    <div class="low mx-auto mb-4 col-md-5 text-center">
      <% if @user.introduction != nil %>
      <%= safe_join(@user.introduction.split("\n"),tag(:br)) %>
      <% end %>
    </div>
  </div>
  <div class="table-responsive">
    <table class='table table-hover table-inverse'>
      <thead>
        <tr>
          <th class="col-7">投稿履歴</th>
          <th class="col-2"></th>
          <th class="col-3"></th>
        </tr>
      </thead>
      <% @posts.each do |post| %>
        <tbody>
          <tr>
            <td>
              <%= link_to post_path(post.id)  do %>
              <%= image_tag post.get_post_image, width: '100%' %>
              <% end %>
            </td>
            <td>
              <%= image_tag post.user.get_profile_image, width: '40px',height: "40px",class:"rounded-circle" %><br>
              <%= link_to post.user.name, user_path(post.user) %>
            </td>
            <td>
              <%= link_to post.title, post %>
              <div id="star-rate<%= post.id%>"></div>
              <script>
                $('#star-rate<%= post.id%>').empty();
                $('#star-rate<%= post.id%>').raty({
                  size      : 36,
                  starOff   : '<%= asset_path('star-off.png') %>',
                  starOn    : '<%= asset_path('star-on.png') %>',
                  starHalf  : '<%= asset_path('star-half.png') %>',
                  half      : true,
                  readOnly  : true,
                  score: <%= post.star %>,
                });
              </script>
            </td>
          </tr>
        </tbody>
      <% end %>
    </table>
  </div>
  <div class="d-flex justify-content-center">
    <%= paginate @posts %>
  </div>
</div>