config/routes.rb
Rails.application.routes.draw do

  root :to =>"homes#top"
  devise_for :users
  
  devise_scope :user do
    get '/users', to: 'devise/registrations#new'
  end
  
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get "followings" => "relationships#followings", as: "followings"
    get "followers" => "relationships#followers", as: "followers"
    get "confirm" => "users#confirm", as: "confirm"
  end

  resources :posts do
    resources :post_comments, only: [:create, :destroy, :edit, :update]
    resource :bookmarks, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  get "users/:id/bookmarks", to: "bookmarks#index", as: :bookmark
  get "users/:id/favorites", to: "favorites#index", as: :favorite

  get ' /tags/:id/posts', to: 'posts#search', as: :tag_posts
  get ' /tags/index', to: 'tags#index', as: :tag

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :post_comments, dependent: :destroy

  has_many :tagmaps, dependent: :destroy
  has_many :tags, through: :tagmaps, dependent: :destroy

  has_many :bookmarks, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_one_attached :post_image

  validates :body, presence: true
  validates :title, presence: true, length: { maximum: 20 }


  def get_post_image
    (post_image.attached?) ? post_image : 'no_image.png'
  end

  def save_tags(post_tags)
    current_tags = self.tags.pluck(:tagname) unless self.tags.nil?
    old_tags = current_tags - post_tags
    new_tags = post_tags - current_tags

    old_tags.each do |old_name|
      self.tags.delete Tag.find_by(tagname: old_name)
    end

    new_tags.each do |new_name|
      post_tag = Tag.find_or_create_by(tagname: new_name)
      self.tags << post_tag
    end
  end

  def bookmarked_by?(user)
    bookmarks.where(user_id: user).exists?
  end

  def favorited_by?(user)
    favorites.where(user_id: user).exists?
  end

  def self.search(search)
    if search
      where(['body LIKE ?', "%#{search}%"])
    else
      all
    end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
before_action :authenticate_user!, only: [:new,:create,:index,:edit,:destroy,:update]

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    tag_list = params[:post][:tagname].delete(' ').delete('　').split(',')
    if params[:post][:post_image].present?
      result = Vision.get_image_data(params[:post][:post_image])
      if result == true
        if @post.save
          @post.save_tags(tag_list)
          redirect_to post_path(@post)
        else
          render :new
        end
      elsif result == false
        flash.now[:alert] = '画像が不適切な疑いがあるため、投稿できません。'
        render :new
      end
    else
      flash.now[:alert] = '画像を選択してください。'
        render :new
    end
  end

  def show
    @post = Post.find(params[:id])
    @post_comment = PostComment.new
    @tags = @post.tags
  end

  def index
  end

  def edit
    @post = Post.find(params[:id])
    @tag_list =@post.tags.pluck(:tagname).join(",")
  end

  def update
    post = Post.find(params[:id])
    tag_list = params[:post][:tagname].delete(' ').delete('　').split(',')
    if params[:post][:post_image].present?
      result = Vision.get_image_data(params[:post][:post_image])
      if result == true
        if post.update(post_params)
          post.save_tags(tag_list)
          redirect_to post_path(post)
        else
          redirect_to request.referer,flash: { alert: "投稿内容に空欄があったため、編集できませんでした。" }
        end
      elsif result == false
        redirect_to request.referer,flash: { alert: "画像が不適切な疑いがあるため、投稿できません。" }
      end
    else
        redirect_to request.referer,flash: { alert: "画像を選択してください。" }
    end
  end

  def destroy
    post = Post.find(params[:id])
    if post.user.id == current_user.id
      post.destroy
      redirect_to user_path(current_user)
    else
      redirect_to request.referer
    end
  end

  def search
    @tag_list = Tag.all.sort {|a,b| b.posts.size <=> a.posts.size}
    @tag = Tag.find(params[:id])
    @posts = @tag.posts.all.order(created_at: :desc).page(params[:page]).per(10)
  end

  private

  def post_params
    params.require(:post).permit(:post_image, :user_id, :body, :title, :star)
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<div class='container'>
  <p style="color:red;"><%= alert %></p>
  <%= form_with model: @post, url: post_path, local: true do |f| %>
     <div class="row">
      <div class="mx-auto text-center mt-3">
        <div class="form-group">
          <%= f.label :画像 %>
          <%= f.file_field :post_image, accept: "image/*" %>
        </div>
        <img id="preview" style="width:40%;">
        <script>
          $('#post_post_image').on('change', function (e) {
            var reader = new FileReader();
            reader.onload = function (e) {
                $("#preview").attr('src', e.target.result);
            }
            reader.readAsDataURL(e.target.files[0]);
          });
        </script>
        <div class="form-group" id="star">
          <%= f.label :star,'評価 ' %>
          <%= f.hidden_field :star, id: :review_star %>
        </div>
        <script>
        $('#star').raty({
          size     : 36,
          starOff:  '<%= asset_path('star-off.png') %>',
          starOn : '<%= asset_path('star-on.png') %>',
          starHalf : '<%= asset_path('star-half.png') %>',
          scoreName: 'post[star]',
          score : 0.5,
          half: true,
        });
        </script>
      </div>
    </div>
    <div class="row">
      <div class="col-12 mt-3 text-center">
        <div class="form-group row col-12 mx-0">
        <%= f.label :タグ, class: "col-12 col-md-3 text-left px-0" %>
        <%= f.text_field :tagname, value: @tag_list, placeholder: "半角カンマ( , )で、複数付けられます！", class: "pl-0 col-12 col-sm-8" %>
        </div>
        <div class="form-group row col-12 mx-0">
          <%= f.label :タイトル, class: "col-12 col-md-3 text-left px-0" %>
          <%= f.text_field :title, placeholder: "タイトル", class: "pl-0 col-12 col-sm-8" %>
        </div>
        <div class="form-group row col-12 mx-0">
          <%= f.label :投稿内容, class: "col-12 col-md-3 text-left align-top px-0" %>
          <%= f.text_area :body, placeholder: "本文", class: "pl-0 col-12 col-sm-8", rows:"10" %>
        </div>
        <div class="form-group mx-auto">
          <%= f.submit "編集する", class: "btn btn-success" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<div class='container'>
  <p style="color:red;"><%= alert %></p>
  <%= form_with model: @post, url: posts_path, local: true do |f| %>
     <div class="row">
      <div class="mx-auto text-center mt-3">
        <div class="form-group">
          <%= f.label :画像 %>
          <%= f.file_field :post_image, accept: "image/*" %>
        </div>
        <img id="preview" style="width:40%;">
        <script>
          $('#post_post_image').on('change', function (e) {
            var reader = new FileReader();
            reader.onload = function (e) {
                $("#preview").attr('src', e.target.result);
            }
            reader.readAsDataURL(e.target.files[0]);
          });
        </script>
        <div class="form-group" id="star">
          <%= f.label :star,'評価 ' %>
          <%= f.hidden_field :star, id: :review_star %>
        </div>
        <script>
        $('#star').raty({
          size     : 36,
          starOff:  '<%= asset_path('star-off.png') %>',
          starOn : '<%= asset_path('star-on.png') %>',
          starHalf : '<%= asset_path('star-half.png') %>',
          scoreName: 'post[star]',
          score : 0.5,
          half: true,
        });
        </script>
      </div>
    </div>
    <div class="row">
      <% if @post.errors.any? %>
        <div style = "color: red;">
          <ul>
            <% @post.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="col-12 mt-3 text-center">
        <div class="form-group row col-12 mx-0">
        <%= f.label :タグ, class: "col-12 col-md-3 text-left px-0" %>
        <%= f.text_field :tagname, placeholder: "半角カンマ( , )で、複数付けられます！", class: "pl-0 col-12 col-sm-8" %>
        </div>
        <div class="form-group row col-12 mx-0">
          <%= f.label :タイトル, class: "col-12 col-md-3 text-left px-0" %>
          <%= f.text_field :title, placeholder: "タイトル", class: "pl-0 col-12 col-sm-8" %>
        </div>
        <div class="form-group row col-12 mx-0">
          <%= f.label :投稿内容, class: "col-12 col-md-3 text-left align-top px-0" %>
          <%= f.text_area :body, placeholder: "本文", class: "pl-0 col-12 col-sm-8", rows:"10" %>
        </div>
        <div class="form-group mx-auto">
          <%= f.submit "投稿する", class: "btn btn-success" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/search.html.erb
<div class="container">
  <div class="my-2">
    <%= link_to "タグ一覧",tag_path,class:"btn btn-sm btn-outline-success ml-3" %>
  </div>
  <div class="table-responsive">
    <table class='table table-hover table-inverse'>
      <thead>
        <tr>
          <th class="col-7"><%= "#{@tag.tagname}" %><%= "　の投稿一覧" %></th>
          <th class="col-2"></th>
          <th class="col-3"></th>
        </tr>
      </thead>
      <% @posts.each do |post| %>
        <tbody>
          <tr>
            <td><%= image_tag post.get_post_image, width: '100%' %></td>
            <td>
              <%= image_tag post.user.get_profile_image, width: '40px',height: "40px",class:"rounded-circle" %><br>
              <%= link_to post.user.name, user_path(post.user) %>
            </td>
            <td>
              <%= link_to post.title, post_path(post) %>
              <div id="star-rate<%= post.id%>"></div>
              <script>
                $('#star-rate<%= post.id %>').empty();
                $('#star-rate<%= post.id %>').raty({
                  size      : 36,
                  starOff   : '<%= asset_path('star-off.png') %>',
                  starOn    : '<%= asset_path('star-on.png') %>',
                  starHalf  : '<%= asset_path('star-half.png') %>',
                  half      : true,
                  readOnly  : true,
                  score: <%= post.star %>,
                });
              </script>
            </td>
          </tr>
        </tbody>
      <% end %>
    </table>
  </div>
  <div class="d-flex justify-content-center">
    <%= paginate @posts %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container">
  <div class="row d-flex">
    <div class="col-12">
      <div class="my-4">
        <strong><%= @post.title %></strong>
        <% if @post.user == current_user %>
          <%= link_to edit_post_path(@post) do %>
            <i class="fas fa-edit" style="color: green;"></i>
          <% end %>
          <%= "/" %>
          <%= link_to post_path(@post), method: :delete, data: { confirm: '削除しますか？' } do %>
            <i class="fas fa-trash" style="color: red;"></i>
          <% end %>
        <% end %>
      </div>
      <%= image_tag @post.get_post_image, width:"100%" %>
      <div id="star-rate<%= @post.id%>"></div>
      <script>
        $('#star-rate<%= @post.id%>').empty();
        $('#star-rate<%= @post.id%>').raty({
          size      : 36,
          starOff   : '<%= asset_path('star-off.png') %>',
          starOn    : '<%= asset_path('star-on.png') %>',
          starHalf  : '<%= asset_path('star-half.png') %>',
          half      : true,
          readOnly  : true,
          score: <%= @post.star %>,
        });
      </script>
      <p class="mt-2 mb-1">タグ：
        <% @tags.each do |tag| %>
          <%= link_to tag.tagname, tag_posts_path(tag.id) %>
          <%= "(#{tag.posts.count})" %>
        <% end %>
      </p>
    </div>
    <div class="col-12">
      <% if user_signed_in? %>
      <div class="row mb-1">
        <div class="mx-3">
          <div id="bookmark_button_<%= @post.id %>">
            <%= render "bookmarks/bookmark", post: @post %>
          </div>
        </div>
        <div class="mx-3">
          <div id="favorite_button_<%= @post.id %>">
            <%= render "favorites/favorite", post: @post %>
          </div>
        </div>
      </div>
      <% end %>
      <div class="mb-2">
        <%= image_tag @post.user.get_profile_image, width: '40px',height: "40px",class:"rounded-circle" %>
        <%= link_to @post.user.name, user_path(@post.user) %>
      </div>
      <div class="ml-3 mb-3">
        <%=safe_join(@post.body.split("\n"),tag(:br))%>
      </div>
    </div>
  </div>
  <% if user_signed_in? %>
    <div>
      <%= form_with model: [@post, @post_comment], local: true do |f| %>
        <%= f.text_area :comment, :rows =>"5", placeholder:"コメント：", class:"form-control mb-3" %>
        <%= f.submit "コメントする",class:"btn btn-success col-sm-3 mb-3" %>
      <% end %>
    </div>
  <% end %>
  <div class="low mb-5">
    <table class='table table-hover table-inverse'>
      <thead>
        <tr>
          <th class="col-4">コメント一覧</th>
          <th class="col-7"></th>
          <th class="col-1"></th>
        </tr>
      </thead>
      <tbody>
        <% @post.post_comments.each do |post_comment| %>
          <tr>
            <td>
              <%= image_tag post_comment.user.get_profile_image, width: '40px',height: "40px",class:"rounded-circle" %><br>
              <%= post_comment.user.name %>
            </td>
            <td>
              <%=safe_join(post_comment.comment.split("\n"),tag(:br))%>
            </td>
            <td>
              <% if post_comment.user == current_user %>
                <%= link_to post_post_comment_path(@post, post_comment), method: :delete do %>
                  <i class="fas fa-trash" style="color:red;"></i>
                <% end %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>