config/routes.rb
Rails.application.routes.draw do

  root :to =>"homes#top"
  devise_for :users
  
  devise_scope :user do
    get '/users', to: 'devise/registrations#new'
  end
  
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get "followings" => "relationships#followings", as: "followings"
    get "followers" => "relationships#followers", as: "followers"
    get "confirm" => "users#confirm", as: "confirm"
  end

  resources :posts do
    resources :post_comments, only: [:create, :destroy, :edit, :update]
    resource :bookmarks, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  get "users/:id/bookmarks", to: "bookmarks#index", as: :bookmark
  get "users/:id/favorites", to: "favorites#index", as: :favorite

  get ' /tags/:id/posts', to: 'posts#search', as: :tag_posts
  get ' /tags/index', to: 'tags#index', as: :tag

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :user_id, uniqueness: { scope: :post_id }
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :user_id, uniqueness: { scope: :post_id }
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :post_comments, dependent: :destroy

  has_many :tagmaps, dependent: :destroy
  has_many :tags, through: :tagmaps, dependent: :destroy

  has_many :bookmarks, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_one_attached :post_image

  validates :body, presence: true
  validates :title, presence: true, length: { maximum: 20 }


  def get_post_image
    (post_image.attached?) ? post_image : 'no_image.png'
  end

  def save_tags(post_tags)
    current_tags = self.tags.pluck(:tagname) unless self.tags.nil?
    old_tags = current_tags - post_tags
    new_tags = post_tags - current_tags

    old_tags.each do |old_name|
      self.tags.delete Tag.find_by(tagname: old_name)
    end

    new_tags.each do |new_name|
      post_tag = Tag.find_or_create_by(tagname: new_name)
      self.tags << post_tag
    end
  end

  def bookmarked_by?(user)
    bookmarks.where(user_id: user).exists?
  end

  def favorited_by?(user)
    favorites.where(user_id: user).exists?
  end

  def self.search(search)
    if search
      where(['body LIKE ?', "%#{search}%"])
    else
      all
    end
  end

end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :comment, presence: true

end

app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tagmaps
  has_many :posts, through: :tagmaps

  validates :tagname, length: { minimum: 1, maximum: 10 }
  
  def self.search(search)
    if search
      where(['tagname LIKE ?', "%#{search}%"])
    else
      all
    end
  end
  
end

app/models/tagmap.rb
class Tagmap < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord

  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower

  has_one_attached :profile_image

  validates :name, length: { minimum: 1, maximum: 10 }, uniqueness: true

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.png'
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @posts = Post.all.order(created_at: :desc).page(params[:page]).per(5).search(params[:search])
    @tag_list = Tag.all.sort {|a,b| b.posts.size <=> a.posts.size}
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
before_action :authenticate_user!, only: [:new,:create,:index,:edit,:destroy,:update]

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    tag_list = params[:post][:tagname].delete(' ').delete('　').split(',')
    if params[:post][:post_image].present?
      result = Vision.get_image_data(params[:post][:post_image])
      if result == true
        if @post.save
          @post.save_tags(tag_list)
          redirect_to post_path(@post)
        else
          render :new
        end
      elsif result == false
        flash.now[:alert] = '画像が不適切な疑いがあるため、投稿できません。'
        render :new
      end
    else
      flash.now[:alert] = '画像を選択してください。'
        render :new
    end
  end

  def show
    @post = Post.find(params[:id])
    @post_comment = PostComment.new
    @tags = @post.tags
  end

  def index
  end

  def edit
    @post = Post.find(params[:id])
    @tag_list =@post.tags.pluck(:tagname).join(",")
  end

  def update
    post = Post.find(params[:id])
    tag_list = params[:post][:tagname].delete(' ').delete('　').split(',')
    if params[:post][:post_image].present?
      result = Vision.get_image_data(params[:post][:post_image])
      if result == true
        if post.update(post_params)
          post.save_tags(tag_list)
          redirect_to post_path(post)
        else
          redirect_to request.referer,flash: { alert: "投稿内容に空欄があったため、編集できませんでした。" }
        end
      elsif result == false
        redirect_to request.referer,flash: { alert: "画像が不適切な疑いがあるため、投稿できません。" }
      end
    else
        redirect_to request.referer,flash: { alert: "画像を選択してください。" }
    end
  end

  def destroy
    post = Post.find(params[:id])
    if post.user.id == current_user.id
      post.destroy
      redirect_to user_path(current_user)
    else
      redirect_to request.referer
    end
  end

  def search
    @tag_list = Tag.all.sort {|a,b| b.posts.size <=> a.posts.size}
    @tag = Tag.find(params[:id])
    @posts = @tag.posts.all.order(created_at: :desc).page(params[:page]).per(10)
  end

  private

  def post_params
    params.require(:post).permit(:post_image, :user_id, :body, :title, :star)
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tag_list = Tag.all.search(params[:search]).page(params[:page]).per(30)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :authenticate_user!, only: [:edit,:update,:confirm]

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.all.order(created_at: :desc).page(params[:page]).per(5)
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def confirm
    @user = current_user
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/"><span>Travelands</span></a>
      <%#= link_to "Travelands", root_path, class:"navbar-brand", data: {"turbolinks" => false} %>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">

<%# ユーザーログイン後のヘッダー　%>
          <% if user_signed_in? %>
            <li class="nav-item text-right">
              <%= link_to new_post_path, class: 'nav-link text-light' do %>
                <i class="fas fa-pen"></i>新規投稿
              <% end %>
            </li>
            <li class="nav-item text-right">
              <%= link_to bookmark_path(current_user), class: 'nav-link text-light' do %>
                <i class="fas fa-bookmark"></i>ブクマ一覧
              <% end %>
            </li>
            <li class="nav-item text-right">
              <%= link_to favorite_path(current_user), class: 'nav-link text-light' do %>
              <i class="fas fa-heart"></i>いいね一覧
              <% end %>
            </li>
            <li class="nav-item text-right">
              <%= link_to user_path(current_user), class: 'nav-link text-light' do %>
              <i class="fas fa-user"></i>マイページ
              <% end %>
            </li>
            <li class="nav-item text-right">
              <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-light' do %>
              <i class="fas fa-sign-out-alt"></i>ログアウト
              <% end %>
            </li>

<%# ログイン前のヘッダー　%>
          <% else %>
            <li class="nav-item text-right">
              <%= link_to new_user_registration_path, class: 'nav-link text-light' do %>
              <i class="fas fa-user"></i>新規登録
              <% end %>
            </li>
            <li class="nav-item text-right">
              <%= link_to new_user_session_path, class: 'nav-link text-light' do %>
              <i class="fas fa-sign-in-alt"></i>ログイン
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Travelands</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>